
package introsde.client.naturalturist.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NaturalTuristWebService", targetNamespace = "http://soap.orchestrator.APP4.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NaturalTuristWebService {


    /**
     * 
     * @return
     *     returns java.util.List<introsde.client.naturalturist.wsdl.Park>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllParks", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetAllParks")
    @ResponseWrapper(localName = "getAllParksResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetAllParksResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getAllParksRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getAllParksResponse")
    public List<Park> getAllParks();

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.client.naturalturist.wsdl.Park
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPark", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SearchPark")
    @ResponseWrapper(localName = "searchParkResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SearchParkResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/searchParkRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/searchParkResponse")
    public Park searchPark(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.client.naturalturist.wsdl.Shed>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSheds", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetAllSheds")
    @ResponseWrapper(localName = "getAllShedsResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetAllShedsResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getAllShedsRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getAllShedsResponse")
    public List<Shed> getAllSheds();

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.client.naturalturist.wsdl.Shed
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchShed", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SearchShed")
    @ResponseWrapper(localName = "searchShedResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SearchShedResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/searchShedRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/searchShedResponse")
    public Shed searchShed(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.RegisterUserResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/registerUserRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/registerUserResponse")
    public Integer registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.client.naturalturist.wsdl.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetAllUsersResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getAllUsersRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getAllUsersResponse")
    public List<User> getAllUsers();

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.client.naturalturist.wsdl.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchUser", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SearchUser")
    @ResponseWrapper(localName = "searchUserResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SearchUserResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/searchUserRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/searchUserResponse")
    public User searchUser(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setUserPreference", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SetUserPreference")
    @ResponseWrapper(localName = "setUserPreferenceResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SetUserPreferenceResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/setUserPreferenceRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/setUserPreferenceResponse")
    public void setUserPreference(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "postReview", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.PostReview")
    @ResponseWrapper(localName = "postReviewResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.PostReviewResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/postReviewRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/postReviewResponse")
    public void postReview(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Review arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.client.naturalturist.wsdl.Review>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getParkReviews", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetParkReviews")
    @ResponseWrapper(localName = "getParkReviewsResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetParkReviewsResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getParkReviewsRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getParkReviewsResponse")
    public List<Review> getParkReviews(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.client.naturalturist.wsdl.Review>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getShedReviews", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetShedReviews")
    @ResponseWrapper(localName = "getShedReviewsResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetShedReviewsResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getShedReviewsRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getShedReviewsResponse")
    public List<Review> getShedReviews(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.client.naturalturist.wsdl.Review>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserReviews", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetUserReviews")
    @ResponseWrapper(localName = "getUserReviewsResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetUserReviewsResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getUserReviewsRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getUserReviewsResponse")
    public List<Review> getUserReviews(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addVote", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.AddVote")
    @ResponseWrapper(localName = "addVoteResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.AddVoteResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/addVoteRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/addVoteResponse")
    public void addVote(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        PlaceVisited arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getParkVote", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetParkVote")
    @ResponseWrapper(localName = "getParkVoteResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetParkVoteResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getParkVoteRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getParkVoteResponse")
    public Double getParkVote(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getShedVote", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetShedVote")
    @ResponseWrapper(localName = "getShedVoteResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetShedVoteResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getShedVoteRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getShedVoteResponse")
    public Double getShedVote(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.client.naturalturist.wsdl.Suggestion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSuggestion", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetSuggestion")
    @ResponseWrapper(localName = "getSuggestionResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.GetSuggestionResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getSuggestionRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/getSuggestionResponse")
    public Suggestion getSuggestion(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.client.naturalturist.wsdl.Park>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchParks", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SearchParks")
    @ResponseWrapper(localName = "searchParksResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SearchParksResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/searchParksRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/searchParksResponse")
    public List<Park> searchParks(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.client.naturalturist.wsdl.Shed>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchSheds", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SearchSheds")
    @ResponseWrapper(localName = "searchShedsResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SearchShedsResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/searchShedsRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/searchShedsResponse")
    public List<Shed> searchSheds(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.client.naturalturist.wsdl.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchUsers", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SearchUsers")
    @ResponseWrapper(localName = "searchUsersResponse", targetNamespace = "http://soap.orchestrator.APP4.introsde/", className = "introsde.client.naturalturist.wsdl.SearchUsersResponse")
    @Action(input = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/searchUsersRequest", output = "http://soap.orchestrator.APP4.introsde/NaturalTuristWebService/searchUsersResponse")
    public List<User> searchUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
